// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZr4KZZzFFJFA69HHKcBpiayb7tt4taKY',
    appId: '1:504837034251:web:c16d14f6997e18bc86920e',
    messagingSenderId: '504837034251',
    projectId: 'kaammitra-87e38',
    authDomain: 'kaammitra-87e38.firebaseapp.com',
    storageBucket: 'kaammitra-87e38.firebasestorage.app',
    measurementId: 'G-8NQH6TKV98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS6M4OTVUpSG0fGVoolUDTXa_Q1GgcWB0',
    appId: '1:504837034251:android:0048766e82a2d05386920e',
    messagingSenderId: '504837034251',
    projectId: 'kaammitra-87e38',
    storageBucket: 'kaammitra-87e38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5AoTk0u_HXGrwjrHocZ5J-m_lH5XuDs',
    appId: '1:504837034251:ios:bc08c134225f9b8786920e',
    messagingSenderId: '504837034251',
    projectId: 'kaammitra-87e38',
    storageBucket: 'kaammitra-87e38.firebasestorage.app',
    iosBundleId: 'com.example.myFriendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr5AoTk0u_HXGrwjrHocZ5J-m_lH5XuDs',
    appId: '1:504837034251:ios:bc08c134225f9b8786920e',
    messagingSenderId: '504837034251',
    projectId: 'kaammitra-87e38',
    storageBucket: 'kaammitra-87e38.firebasestorage.app',
    iosBundleId: 'com.example.myFriendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZr4KZZzFFJFA69HHKcBpiayb7tt4taKY',
    appId: '1:504837034251:web:1f732bd1eda0872986920e',
    messagingSenderId: '504837034251',
    projectId: 'kaammitra-87e38',
    authDomain: 'kaammitra-87e38.firebaseapp.com',
    storageBucket: 'kaammitra-87e38.firebasestorage.app',
    measurementId: 'G-86PSN8C6SR',
  );
}
